language: python
python:
  - "3.5"
env:
  matrix:
    # pyethereum 1.6.x
    - TOX_POSARGS="-e py27-ethereum16 -e py34-ethereum16 -e py35-ethereum16"
    # pyethereum 2.0.x
    - TOX_POSARGS="-e py27-ethereum20 -e py34-ethereum20 -e py35-ethereum20"
    - TOX_POSARGS=flake8
cache:
  pip: true
install:
  - "travis_retry pip install pip setuptools --upgrade"
  - "travis_retry pip install tox"
script:
  - tox $TOX_POSARGS
after_script:
  - cat .tox/$TOX_POSARGS/log/*.log
